version: '3.8'

services:
  postgres:
    container_name: "psql"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - database-drive:/var/lib/postgresql/data
    networks:
      - local.network

  backend:
    container_name: "backend"
    build:
      context: ../../Backend/.
      dockerfile: Interview.Backend/Dockerfile
      args:
        Database: ${DATABASE}
        ConnectionString: ${CONNECTION_STRING}
        ClientId: ${CLIENT_ID}
        ClientSecret: ${CLIENT_SECRET}
        SwaggerPrefix: ""
    ports:
      - '8800:8800'
    environment:
      - ASPNETCORE_URLS=http://+:8800
      - ASPNETCORE_ENVIRONMENT=${CSHARP_ENVIRONMENT}
    volumes:
      - backend-drive:/app/
    depends_on:
      - postgres
    networks:
      - local.network

networks:
  local.network:
    driver: bridge
    
volumes:
  backend-drive:
  database-drive:
