version: "3.8"

services:
  
  postgres:
    platform: linux/amd64
    container_name: "database"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: devpav
      POSTGRES_PASSWORD: devpav